version: 2.1

jobs: # a basic unit of work in a run
  build-and-test:
    macos:
      xcode: 13.4.1
    steps:
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 12
            SCAN_SCHEME: Circle-Ci-Test-App

workflows:
  test_build:
    jobs:
      - build-and-test