version: 2.1

jobs:
  test:
    macos:
      xcode: 13.4.1
    steps:
      - checkout
      - run:
          name: Run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 12
            SCAN_SCHEME: Circle-Ci-Test-App

workflows:
    test-workflow:
      jobs:
        - test